version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://192.168.100.5:3000
    container_name: amarumed-front
    ports:
      - "8080:80"
    environment:
      - PROXY=http://192.168.100.5:3000
