// Copyright Andres Grijalva 2020. All Rights Reserved.
// Node module: amarumed
// This file is licensed under the MIT License.
// License text available at https://opensource.org/licenses/MIT

export * from './medical-record-vital-sign.controller'
export * from './medical-record-diagnostic.controller'
export * from './medic-medical-specialty.controller'
export * from './patient-medical-record.controller'
export * from './medic-medical-record.controller'
export * from './disease-disease-type.controller'
export * from './disease-type-disease.controller'
export * from './medical-record-cros.controller'
export * from './medical-record-exam.controller'
export * from './patient-antecedent.controller'
export * from './medical-record-rpe.controller'
export * from './exam-exam-type.controller'
export * from './exam-type-exam.controller'
export * from './medical-record.controller'
export * from './option-group.controller'
export * from './profile-user.controller'
export * from './role-module.controller'
export * from './vital-sign.controller'
export * from './permission.controller'
export * from './user-role.controller'
export * from './patient.controller'
export * from './storage.controller'
export * from './company.controller'
export * from './profile.controller'
export * from './account.controller'
export * from './option.controller'
export * from './module.controller'
export * from './group.controller'
export * from './user.controller'
export * from './role.controller'
export * from './ping.controller'
export * from './log.controller'
export * from './user-medic.controller'
